### PR TITLE
Allow empty translations

### LINKED ISSUE #429: Displays namespace:key if translation key is empty
When key empty, like `"key": ""`, translate function returns "`(namespace):key`".
When key contains translation or space, it works like expected.
Shouldn't it return empty string instead of namespace:key when key is empty string?

### PR DESCRIPTION
**Pull request by j-schumann**
This PR fixes #429 and allows an empty string to be returned 

a) if the translation was explicitly defined empty: `"i18nkey": ""`

b) if the translation only consists of an interpolation and the interpolation param was empty:
`"i18nkey": "{{name}}"` + `t("ns:i18nkey", {name: ""})`

### CODE REVIEW

**Comment by aralroca** [comment]
@j-schumann Thanks for the contribution! 🙏 You are on fire! I think this should be configurable, otherwise it is a breaking change. There are cases where it is interesting to show on the page the keys of the missing ones to locate them.

Maybe we could make a property in the configuration, for example `displayKeysOfMissingTranslations` (maybe find a shorter one). What do you think?

**Review by aralroca — APPROVED** [review]
@j-schumann Ignore what I said. For a moment I understood something else. I'm fine with that. I think we can upload it in 1.0.2 then. Thank you!

**Comment by aralroca** [comment]
@allcontributors please add @j-schumann for code

**Comment by aralroca** [comment]
@j-schumann I prereleased [1.0.2-canary.4](https://github.com/vinissimus/next-translate/releases/tag/1.0.2-canary.4) with this change if you want to start using it

**Comment by j-schumann** [comment]
Thanks @aralroca, I built a package from my fork including all 3 PRs to move forward with my project as I need all of those features ;-)

Thanks for merging!

**Comment by sapjax** [comment]
This feature is not effective anymore, anyone knows what happend?

**Comment by aralroca** [comment]
In witch version @sapjax ?

**Comment by sapjax** [comment]
> In witch version @sapjax ?

1.3.3

**Comment by acentfrio** [comment]
greeting everyone.

how the one may force to fallback to key value if the key doesn't have yet a translation?

**Comment by j-schumann** [comment]
@acentfrio see the discussion in https://github.com/aralroca/next-translate/issues/429 - if a key does not have a translation (e.g. does not exist in your translation file) the key is returned as fallback. If you have the key in your translation file but did not specify a string but only "" (empty string), then this empty string is returned (as you specified it).
Solution would be to remove the empty string(s) if you want them to be displayed as "untranslated".

My understanding of the current implementation is, that there is no option like [returnEmptyString](https://www.i18next.com/overview/configuration-options#translation-defaults) for now.

**Pull request merged**
