### PR TITLE
Fix default namespace not working for fallback keys, fix types

### PR DESCRIPTION
**Pull request by andrehsu**

### CODE REVIEW

**Comment by andrehsu** [comment]
@aralroca Is there some reason why all the types are defined in index.tsx, and not defined on the functions/classes themselves? I feel like a lot of the benefit of Typescript's static analysis is lost when the library uses so much type casting.

**Comment by andrehsu** [comment]
I took the liberty of replacing type casts with return type and type parameters where it makes sense, to make it more idiomatic Typescript.

**Review by aralroca — APPROVED** [review]
@andrehsu  thanks a lot for your contribution! It's amazing!  About the TypeScript types, they are in the index.ts maybe because of my lack of TypeScript experience. If you think it could be better, feel free to PR!

**Comment by aralroca** [comment]
@allcontributors please add @andrehsu for code

**Comment by aralroca** [comment]
@andrehsu I prepublished [1.0.2-canary.8](https://github.com/vinissimus/next-translate/releases/tag/1.0.2-canary.8) with your change if you want to start using it

**Pull request merged**
