### PR TITLE
Add next.js i18n routing support

### PR DESCRIPTION
**Pull request by aralroca**
Closes https://github.com/vinissimus/next-translate/issues/284
Closes https://github.com/vinissimus/next-translate/issues/250
Closes https://github.com/vinissimus/next-translate/issues/248
Closes https://github.com/vinissimus/next-translate/issues/245
Closes https://github.com/vinissimus/next-translate/issues/231
Closes https://github.com/vinissimus/next-translate/issues/209
Closes https://github.com/vinissimus/next-translate/issues/208
Closes https://github.com/vinissimus/next-translate/issues/204
Closes https://github.com/vinissimus/next-translate/issues/169

Released under <s>`0.19.0-experimental.1`</s> **`0.19.0-experimental.6`**

### CODE REVIEW

**Comment by aralroca** [comment]
I prereleased `0.19.0-experimental.2` with the latest changes.

**Comment by BjoernRave** [comment]
Because I am using https://github.com/FormidableLabs/urql/tree/main/packages/next-urql, which uses `getInitialProps` under the hood to fetch data, I am getting the following error:
```
Error: You can not use getInitialProps with getStaticProps. To use SSG, please remove your getInitialProps
```

**Comment by aralroca** [comment]
> Because I am using https://github.com/FormidableLabs/urql/tree/main/packages/next-urql, which uses `getInitialProps` under the hood to fetch data, I am getting the following error:
> 
> ```
> Error: You can not use getInitialProps with getStaticProps. To use SSG, please remove your getInitialProps
> ```

Thanks for the feedback @BjoernRave. I'm going to think about how I can solve this case. When the getInitialProps is done in another file different from the page it is a missing case. Well seen.

**Comment by BjoernRave** [comment]
Not sure if related to this PR, but I also get these in the console, although the key exists in my locale files:
```
[next-translate] "common:yearly" is missing in current namespace configuration. Try adding "yearly" to the namespace "common".
```

**Comment by aralroca** [comment]
> Not sure if related to this PR, but I also get these in the console, although the key exists in my locale files:
> 
> ```
> [next-translate] "common:yearly" is missing in current namespace configuration. Try adding "yearly" to the namespace "common".
> ```

Mmm. Looks related to the last release 0.18. The logger stills the same on 0.19. Anyway thank you to report it!

**Comment by aralroca** [comment]
Prereleased `0.19.0-experimental.3`, @BjoernRave now it should use a `getInitialProps`, however now I found another bug related with `getIntialProps`: https://github.com/vercel/next.js/issues/18396

**Pull request merged**
