### PR TITLE
Add options object for t function and returnObjects option 

### PR DESCRIPTION
**Pull request by bickmaev5**
Add options for t function for using like here https://www.i18next.com/translation-function/objects-and-arrays

for example we have locale like this
```
        'template-array': [
          {title: 'Title 1'},
          {title: 'Title 2'},
          {title: 'Title 3'}
        ],
```

and we need it in component as Array by returnObject option

```
const items = t('ns:template-array', {}, { returnObjects: true });
```

and use this array like this

```
{items.map(i => `${i.title} `)}
```

issue: https://github.com/vinissimus/next-translate/issues/157

### CODE REVIEW

**Comment by aralroca** [comment]
Thanks for your contribution @bickmaev5 . Later when I'll have time I'm going to review it carefully!

**Comment by bickmaev5** [comment]
I think in my implementation there will be problems with interpolation, we will need to think what to do with it

**Comment by aralroca** [comment]
@bickmaev5 I'm sorry it took me so long to look at this. LGTM! Thank you for this contribution!

**Comment by aralroca** [comment]
@all-contributors add @bickmaev5 for code

**Pull request merged**
