### PR TITLE
add revalidate property

### PR DESCRIPTION
**Pull request by bmvantunes**
This will enable ISR (Incremental Static Regeneration). Useful when the translations leave outside the GitHub repository in a service like localazy or locize #754

### CODE REVIEW

**Comment by bmvantunes** [comment]
This is linked with issue #754

**Comment by bmvantunes** [comment]
Not 100% sure if I should call the property `revalidate` or `defaultRevalidate`. Any suggestions?

**Review by aralroca — APPROVED** [review]
Thanks for your contribution. Looks good for me!

**Comment by aralroca** [comment]
> Not 100% sure if I should call the property `revalidate` or `defaultRevalidate`. Any suggestions?

Both are correct. `revalidate` for me is OK. 
 Maybe `defaultRevalidate` or `revalidateFallback` are more descriptive. However for me is better a short name with a great description because also `defaultRevalidate` can be confuse, because this default is only for pages without getServerSideProps or getInitialProps, etc.

**Comment by aralroca** [comment]
@all-contributors please add @bmvantunes for code

**Comment by bmvantunes** [comment]
Thank you very much @aralroca 

PS - We forgot to pass the "revalidate" property to the webpack loader (fixed on #759)

**Pull request merged**
