### PR TITLE
Feature: Interpolation Format, implements #266

### PR DESCRIPTION
**Pull request by j-schumann**
This PR implements the requested feature from #266 

* The user can supply a new config option `interpolation.format` which accepts a function
* This formatter is called if an interpolation with a format name is found: `{{param, format}}`

What this PR does/changes:
* supplied the current locale in `getT` and `I18nProvider`
* patched the locale through to transCore.interpolation and objectInterpolation
* extended the interpolation regex to allow a comma-separated format
* call the formatter if a format is found
* Readme updated
* Tests implemented

Review requested for:
* Is the updated regex safe enough?
* Is the allowed naming for formats acceptable? Currently [\w-] == letters and hyphens.
* Is the updated readme acceptable? (description & position of the new chapter)
* Are there issues visible with browser compatibility? (Probably not, no uncommon regex-features used like named capture groups for the replace() callback)
* Are there issues with performance?
* Does it cause unwanted side effects by adding `lang` as parameter to transCore? E.g. causing unwanted re-renders through changed props.

### CODE REVIEW

**Comment by kimlima** [comment]
👍

**Comment by j-schumann** [comment]
@aralroca Hi, could you please re-open, as canary exists again?

**Comment by aralroca** [comment]
It was unintentionally closed

**Comment by j-schumann** [comment]
> It was unintentionally closed

@aralroca When will work on 1.1.0 start so this can be merged? ;-)

**Comment by aralroca** [comment]
Sorry, I deleted the canary branch and the PR was closed. I have reopened it. Yes, the idea is to prioritize issues, the ideal would be to make another patch version (1.0.5) before 1.1.

**Comment by j-schumann** [comment]
Hello @aralroca,
what is the status for this, did work on 1.1.0 start?

Would it be possible to use a workflow that does not delete the branch for each new release? Or to have a real dev branch that keeps the unfinished work? It would be easier to not always having to fix conflicts occuring when later PRs are merged.

When you reopen this, could you please fix further conflicts, I did this this multiple times now and have unfortunately no time and no insight into the intention of the other PRs to fix them again.

**Comment by aralroca** [comment]
@j-schumann sorry. In these releases we are focused on bugfixes so for the moment we don't want to introduce new features, but for 1.1.0 I would like if we could merge this PR. Don't worry about conflicts 👍.

**Pull request closed without merging**
