### PR TITLE
Fix imports from webpack loader in windows

### PR DESCRIPTION
**Pull request by aralroca**
https://github.com/vinissimus/next-translate/issues/129

@vimutti77 can you confirm that the examples of this branch are working on windows now? 🙏

- https://github.com/vinissimus/next-translate/tree/fix-windows

### CODE REVIEW

**Comment by vimutti77** [comment]
I get this error when running "yarn dev" and opening the index page.
```
error - ./node_modules/next/dist/pages/_app.js:2:2
Module not found: Can't resolve 'C:Users♂yDocuments
ext-translateexampleasici18n'
null
Error: Cannot find module '__MY_DRIVE__\next-translate\examples\basic\.next\server\pages-manifest.json'
```

**Comment by aralroca** [comment]
@vimutti77 I have fixed the imports using an alias. Could you confirm if the examples of this branch work for you now? Thank you very much for everything! 🙏

**Comment by heshamz** [comment]
@aralroca Do you think is better to use path.join instead alias?

**Comment by aralroca** [comment]
@heshamz IMHO it is much simpler with the alias, makes the code easier to maintain, and makes it much easier to test the generated templates. Do you think there are any contraindications for using the alias? The only one I can think of is possible collision with existing aliases, but that's why I've put a name that is difficult for other libraries to use _(`@next-translate-root`)_. Thanks!

**Comment by heshamz** [comment]
@aralroca Agree that alias is simpler, as long as it won't cause conflict and (@next-translate-root) is a safe choice.

**Comment by vimutti77** [comment]
@aralroca I tested it and it works 🎉🎉 🎉

**Pull request merged**
