### PR TITLE
Add new property `extensionsRgx` to config

### PR DESCRIPTION
**Pull request by berndartmueller**
To be able to use custom Next.js page extensions (https://github.com/vercel/next.js/issues/8454#issuecomment-560432659), a new property `extensionsRgx` is added to the i18n configuration.

# How to use

// i18n.js

```
module.exports = {
  extensionsRgx: /\.(page|api)\.(tsx|ts|js|mjs|jsx)$/,
  ...
}
```

### CODE REVIEW

**Review by aralroca — APPROVED** [review]
@berndartmueller sounds good! And welcome as a first time contributor!! 

Please, would you add the property in the configuration table of README.md docs? Thank you very much!!

**Comment by berndartmueller** [comment]
> Please, would you add the property in the configuration table of README.md docs? Thank you very much!!

Sure! Just pushed the change.

@aralroca Thanks for your super quick response!

**Review by aralroca — APPROVED** [review]

**Comment by aralroca** [comment]
@berndartmueller I pre-released [1.0.7-canary.1](https://github.com/vinissimus/next-translate/releases/tag/1.0.7-canary.1) with this change if you want to start using it. It will be released on the next release.

**Comment by aralroca** [comment]
@allcontributors please add @berndartmueller for code

**Pull request merged**
