### PR TITLE
Fix: nested middleware detection

### LINKED ISSUE #752: error - TypeError: result.response.headers is not iterable
What version of Next.js are you using?
12.0.7 

What version of Node.js are you using?
v16.13.1

What browser are you using?
Edge

What operating system are you using?
windows 11

How are you deploying your application?
next dev

I used stable ver and 1.3.0-canary.7

Describe the Bug
I setup lib as normal with the new nextjs ver and use normal middleware under ./pages but the lib throw and error - TypeError: result.response.headers is not iterable when add middleware file and when remove this file get work 
I use next js with typescript 

Expected Behavior
I expected to see the application running without any error and loaded translated

To Reproduce
create middleware file under pages and run yarn dev

i18n.js

```
module.exports = {
  locales: ['en-US', 'en-EG', 'ar-EG', 'en-SA', 'ar-SA', 'en-AE', 'ar-AE'],
  defaultLocale: 'en-US',
  localeDetection: true,
  pages: {
    '*': ['common'],
    // '/': ['common'],
    // '/about': ['about'],
  },
  // interpolation: {
  //   prefix: '${',
  //   suffix: '}',
  // },
  logBuild: true,
  loadLocaleFrom: (l, n) =>
    import(`./public/locales/${l}/${n}`).then((m) => m.default),
};

```

And /pages/_middleware.ts:
```

import type { NextRequest, NextFetchEvent } from 'next/server';
import { getToken } from 'next-auth/jwt';
import { NextResponse } from 'next/server';

export default async function Middleware(req: NextRequest | any, ev: NextFetchEvent) {
  console.log(`Middleware req: ${JSON.stringify(req)}`);
  console.log(`Middleware ev: ${JSON.stringify(ev)}`);
  const secret = process.env.SECRET;

  if (req.nextUrl.pathname === '/middleware-protected') {
    const session = await getToken({ req, secret });
    console.log(`Middleware session: ${JSON.stringify(session)}`);

    // You could also check for any property on the session object,
    // like role === "admin" or name === "John Doe", etc.
    if (!session) return NextResponse.redirect('/api/auth/signin');
    // If user is authenticated, continue.
  }

  return NextResponse.next();
}

```

The issue is happen when add async await to fun I think not handled async functions

### PR DESCRIPTION
**Pull request by MrPumpking**
Fixes #752

https://github.com/vinissimus/next-translate/blob/49f580c6d292712a0720a104de3b487e7c11d4ae/src/plugin/utils.ts#L48

Currently the code responsible for middleware detection incorrectly assumes that we should ignore the page only if the **path** (the variable is named `page` but it actually is the file path) starts with `_middleware`. So if we place our middleware inside of a directory in the `pages` folder then the value of `page` would be `/directoryName/_middleware`, and this line would return false.

This PR fixes this problem by extracting the file name from the file path and then checking if the actual name starts with `_middleware.`. It also changes the variable name from `page` to `pageFilePath` to better represent the value we're working with and introduces a simple suite of tests for the `isPageToIgnore` function.

Due to an [upcoming change to Next](https://nextjs.org/docs/messages/middleware-upgrade-guide#no-nested-middleware), which removes the nested middleware, I have also added the new root primary middleware detection to the function (root middleware is placed directly in the `pages` folder and named `middleware.js` or `middleware.ts` - no underscore). I think we should decide whether we want to keep the support for the old middleware system (as it was in beta), or remove it and keep only the final root middleware support.

### CODE REVIEW

**Review by aralroca — APPROVED** [review]
LGTM! Thanks and welcome as first time contributor @MrPumpking

**Comment by aralroca** [comment]
@all-contributors please add @MrPumpking for code

**Comment by aralroca** [comment]
@MrPumpking I prereleased [1.5.0-canary.3](https://github.com/vinissimus/next-translate/releases/tag/1.5.0-canary.3) with your change, please confirm that this version is working fine! Thanks a lot

**Comment by Dragate** [comment]
Next.js (stable) middleware is located next to pages folder, not inside.

**Comment by MrPumpking** [comment]
> Btw, stable middleware is located next to pages folder, not inside.

Yes, I've realised that after this has been merged, there's no need to check for the `middleware.ts` now

**Pull request merged**
