### PR TITLE
use correct syntax for parameter

### PR DESCRIPTION
**Pull request by BjoernRave**

### CODE REVIEW

**Comment by aralroca** [comment]
Thank you! I change it so fast! I'll add tests about this!

**Comment by BjoernRave** [comment]
@aralroca also I just tried `0.10.1` and I get the following error: 

```
ERROR in /Users/bjoern/projects/inventhora/frontend/pages/en/partner/[id]/index.tsx(17,1):
17:1 Cannot assign to 'Page' because it is not a variable.
    15 | }
    16 | 
  > 17 | Page = Object.assign(Page, { ...(C as any) })
       | ^
    18 | 
```

**Comment by aralroca** [comment]
Thanks @BjoernRave, the PR is already merged. I already did the release 0.10.3 including this fix.

**Comment by aralroca** [comment]
BTW @BjoernRave ; Welcome as a contributor 😄🎉

**Pull request merged**
