### PR TITLE
Add more information regarding listing all locales when using the i18n.js instead of i18n.json

### PR DESCRIPTION
**Pull request by luisgserrano**
Hi everyone,

I've started to use this library on a new project and I ended up using the `i18n.js` configuration file instead of the `i18n.json` one.

To be able to change the language, the `README` only has an example on how to access the locales list for the `i18n.json` and since with the `i18n.js` we need to use the `next.JS` router, I think it would be nice to add how to access the `locales` list using `next.JS` router to the documentation.

Hope it helps :)

### CODE REVIEW

**Review by aralroca — CHANGES_REQUESTED** [review]
@luisgserrano You can use the `useRouter` in both cases, with `i18n.js` or `i18n.json`. The locales in `useRouter` are from Next.js v10 and this library (next-translate) exists from before v10. I'm fine with updating the example to `useRouter`, but I wouldn't say it's exclusive to `i18n.js`.

**Comment by luisgserrano** [comment]
@aralroca You are completely right. I've rewrote the description to better describe the example.

**Review by aralroca — APPROVED** [review]
Thanks 🙏

**Comment by aralroca** [comment]
@allcontributors please add @luisgserrano for documentation

**Pull request merged**
