### PR TITLE
Add TransText component to allow Trans behaviour for strings

### PR DESCRIPTION
**Pull request by dndhm**
Because `Trans` handles `useTranslation` internally, it means it cannot easily be used in conjunction with `returnObjects` when mapping over arrays of values containing components:

```
{
  "content-list": [
    "List of <0>things</0>",
    "with <1>variously</1> nested",
    "components and <2><1>content</1></2>!"
  ]
}
```

```
const contentList = t('someNamespace:content-list', {}, { returnObjects: true });
```

Rather than extending and overloading `Trans`, I am using a simple text-only version of it in a project locally, which I feel could be usefully added to the core package:

```
{contentList.map((listItem: string) => (
  <TransText
    text={listItem}
    components={[
      <a href="some-url" />,
      <b />,
      <em />,
    ]}
  />
)}
```

The functionality of `Trans` remains unchanged. I have hoisted `formatElements` into a separate file so it can be used by both `Trans` and `TransText`.

### CODE REVIEW

**Comment by AndrewBestbier** [comment]
Would love to have this in!

**Comment by dndhm** [comment]
Thanks @AndrewBestbier!

Do any maintainers have am opinion on this?

**Comment by aralroca** [comment]
Related with this discussion: https://github.com/vinissimus/next-translate/discussions/626

Sorry for taking so long, I had an accident and have been in the hospital for a while. Now that I'm back, I'll take a good look at the PR during this week. I think it's a good idea, but I don't know if there was a more practical solution, I'll check it out.

**Comment by dndhm** [comment]
No problem - sorry to hear about your accident!

**Comment by aralroca** [comment]
Sorry, I removed the canary branch when I made the release by accident and the PRs that were open have been closed. I am committed to review the PR during this week. Sorry for the delay. And thank you very much for the contribution.

**Comment by dndhm** [comment]
No worries - let me know if you have any feedback I can help out with!

**Review by aralroca — APPROVED** [review]
Thank you very much for your contribution!  🤗

Sorry for the delay in reviewing the PR. I see the PR very well 😊

I think it's good that there is a different component just for this and not give a thousand options to the `Trans` component, so who uses the `Trans` does not import code and avoid conflicts with `i18nKey` and `text`. Therefore, perfect👏

Do you think it would be too much to ask to add in the README information about the TransText component 🤔? If it is too much trouble I can merge the PR and we will do it.

**Comment by dndhm** [comment]
Hi @aralroca - sure, no problem! Thanks for the kind review. Looking forward to getting this merged.

I'll add a README update to this PR in the next day or two.

**Review by aralroca — APPROVED** [review]

**Comment by aralroca** [comment]
@all-contributors please add @dndhm for code, test and documentation

**Comment by aralroca** [comment]
Thanks @dndhm !! I prereleased on [1.3.0-canary.3](https://github.com/vinissimus/next-translate/releases/tag/1.3.0-canary.3). It will be finally released on the next release 1.3.0

**Comment by dndhm** [comment]
Great, thanks! Happy to be involved! 🎉

**Pull request merged**
