### PR TITLE
Add redirect from '/en' to '/'

### PR DESCRIPTION
**Pull request by Faulik**
Based on this https://github.com/vinissimus/next-translate/issues/147 discussion.
Some prettier style changes are applied on hasky, so kept them.

### CODE REVIEW

**Comment by aralroca** [comment]
I'm going to pre-release this in `0.16.0-canary.1` if you want to try it in a real project. This will be released on `0.16.0` (probably today or tomorrow).

**Comment by tronjsdev** [comment]
Hi, correct me if I wrong, it seems that currently  `redirectToDefaultLang` only works in "build step" right?

**Comment by aralroca** [comment]
More or less @tronjsdev... `redirectToDefaultLang` it also works using a custom server.  However if you are following this example:

* https://github.com/vinissimus/next-translate/tree/master/examples/with-dynamic-routes

It's not fully supported by **next-translate** yet. There is an open issue here https://github.com/vinissimus/next-translate/issues/129 to evolve this.

**Comment by aralroca** [comment]
@all-contributors add @Faulik for code

**Pull request merged**
