### PR TITLE
allow disable lang on Link

### PR DESCRIPTION
**Pull request by BjoernRave**
I am using api routes to handle auth0. When routing to those routes, it results in a 404, due to the language being added. 

This adds the option to disable the addition of the language.

### CODE REVIEW

**Comment by BjoernRave** [comment]
@aralroca The `builder › files tree › should build all the necessary files for all languages` test is failing, not sure why

**Comment by aralroca** [comment]
@BjoernRave looks that via GitHub Actions all tests passed well... I'm going to take a look at this test. But your code looks good! Thank you a lot for your contribution!!

**Comment by BjoernRave** [comment]
@aralroca np, just saw, that I also committed the `yarn.lock` file, not sure if it introduces any problems

**Comment by aralroca** [comment]
Don't worry, I just updated all deps before the 0.12.0 release 🙂

**Comment by aralroca** [comment]
@all-contributors add @BjoernRave for code

**Pull request merged**
