### PR TITLE
Add support for nsSeparator and defaultNS

### PR DESCRIPTION
**Pull request by testerez**
`nsSeparator` option was required so that I can use natural text as i18n keys. `defaultNS` was a bonus 🙂

| Option            | Description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | Type                            | Default                                                                         |
| ----------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------- | ------------------------------------------------------------------------------- |
| `nsSeparator`   | char to split namespace from key. You should set it to `false` if you want to use natural text as keys.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | `string` &#124; `false` | `':'`
| `defaultNS`   | default namespace used if not passed to `useTranslation` or in the translation key.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   | `string` | `undefined`

Also added `ns` prop in `Tans` component because I needed a way to set the namespace when `nsSeparator=false`

Note that those options are available in i18next:
- https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
- https://react.i18next.com/latest/trans-component#trans-props

### CODE REVIEW

**Comment by testerez** [comment]
Hello @aralroca, could I get a review on this one 🙏
Thanks!

**Review by aralroca — APPROVED** [review]
I see everything fine @testerez. Thanks for your contribution 😊

I just have one question: is the `nsSeparator` required as `false`? If the `Trans` component has `ns` or `useTranslation(ns)` then it doesn't look at the separator, then when does the `nsSeparator=false` make sense? Thanks.

**Comment by testerez** [comment]
> I just have one question: is the `nsSeparator` required as `false`? If the `Trans` component has `ns` or `useTranslation(ns)` then it doesn't look at the separator, then when does the `nsSeparator=false` make sense? Thanks.

If `nsSeparator !== false` then you always have the option to add a namespace in the key. It will alway the firs key found in this order:

**Comment by aralroca** [comment]
> is required so that the key won't ever be parsed to find a namespace in it

I'm still in doubt...

Ideally, the key won't ever be parsed to find a namespace in it when:
- `ns` param exist in `Trans` component:  `<Trans ns="ns" />`
- `ns` param exist in `useTranslation` hook: `useTranslation(ns)`

That is to say, if the parameter `ns` exists it would be equivalent to `nsSeparator=false` and the namespace inside the key would not be looked at.

I understand that this is the current behavior. So I have trouble understanding what `nsSeparator=false` is doing.

Thanks 👏

**Comment by testerez** [comment]
As you can see [here](https://github.com/vinissimus/next-translate/pull/739/files#diff-a9eb07a138186fa19b59484ddce160bdbd2fa0657ed97265b0a58800ffc7fe2bR37) I use in priority the namespace sed in the key itself. Which IMO is to expected. Since the closer to the key is the most specific. A believe this is also how i18next behaves.
Also, `nsSeparator` is used not only for `<Trans/>` but also for `t()`. And finally, as I added the option to have a default namespace, this is another level of fallback to get a namespace.

**Comment by aralroca** [comment]
Okay, now I understand. Thanks for the clarification, now I see it perfectly. Thank you!

**Comment by aralroca** [comment]
@all-contributors please add @testerez for code

**Comment by aralroca** [comment]
@testerez I prereleased this in [1.3.0-canary.4](https://github.com/vinissimus/next-translate/releases/tag/1.3.0-canary.4)!

**Comment by testerez** [comment]
Thanks @aralroca! 👏

**Pull request merged**
