### PR TITLE
Allow custom loggers to always log

### PR DESCRIPTION
**Pull request by edwinveldhuizen**
I have my custom logger that actually generates missing keys in the files:
```
function missingKeyLogger({
    namespace,
    i18nKey
}) {
    if (process.env.NODE_ENV === 'production') return

    // This means that instead of "ns:value", "value" has been misspelled (without namespace)
    if (!i18nKey) {
        console.warn(
            `[i18n] The text "${namespace}" has no namespace in front of it.`
        );
        return
    }

    // Try creating the missing key
    if (fs.writeFileSync) {
        console.warn(
            `[i18n] "${namespace}:${i18nKey}" is missing in current namespace configuration. Trying to add "${i18nKey}" to the namespace "${namespace}".`
        );
        locales.forEach((locale) => {
            loadLocaleFrom(locale, namespace)
                .then((file) => {
                    const path = getLocaleFile(locale, namespace);
                    if (file[i18nKey]) return;
        
                    file[i18nKey] = i18nKey;
                    let result = dot.object(file);
                    result = orderKeys(result);
        
                    if (file === result) return;
                    fileCache[locale][namespace] = result;
                    fs.writeFileSync(path, JSON.stringify(result, null, 4) + '\n');
                    console.warn(
                        `[i18n] "${i18nKey}" succesfully added to ${locale}/${namespace}.`
                    );
                });
        });
        return;
    }

    console.warn(
        `[i18n] "${namespace}:${i18nKey}" is missing in current namespace configuration. Please add "${i18nKey}" to the namespace "${namespace}".`
    );
}
```

The only issue I have, currently logging is disabled unless `typeof window !== 'undefined'`. 
While actually, I need my logger function to run from server-level

### CODE REVIEW

**Review by aralroca — CHANGES_REQUESTED** [review]
This is a good idea. Maybe to avoid creating a breaking change we could create a new property to decide where the logger is executed: 'node' | 'browser' | 'both'. And even apply it to the default logger.

**Comment by edwinveldhuizen** [comment]
@aralroca applied your suggestion :)

**Review by aralroca — APPROVED** [review]
LGTM!

**Comment by aralroca** [comment]
@edwinveldhuizen thanks for your contribution. I create a new prerelase [1.3.6-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.3.6-canary.2) with your change if you want to use it. It will be finally released on 1.3.6 release

**Pull request merged**
