### PR TITLE
alias slugs & getTranslatedLink

### PR DESCRIPTION
**Pull request by tonxxd**
Hi,
thanks again for this awesome tool.
I had the need to create localized slugs for some languages
so for instance

static page
     en --> /contact
     it   --> /contatti

dynamic route
     en --> /products/[id].js
     it   --> /prodotti/[id].js

I created a new field in i18n.json called alias which can be used for this purpose
If you want to translate the slug of a page just add a new key corresponding to the page name in the pages_ folder and a list of translations in various languages. You don't have to include the slug translation for every language or for all pages.

```{
...
   "alias": {
          "/contact": {
                "it": "/contatti"
          },
          "/products/[id]": {
                "it": "/prodotti/[id]"
          }
          ...
   }
...
}
```
I have also changed the Link and Router components (and also the fixHref and fixAs files).
In addition, I created a new function
   `getTranslatedLink`
which returns the correct translation in another language given an alias and the target language. This is useful when for instance you want to include a link to the translate versions of the current page in the header component passing the router route and path without caring about aliases

It works without problems on the website I shared with you in issue [116](https://github.com/vinissimus/next-translate/issues/116)

Tests (sorry, I'm not used to them) and documentation are missing, I can write the latter if you think this could be a feature to merge

Hope it helps

### CODE REVIEW

**Comment by aralroca** [comment]
First of all, thank you for your first contribution @tonxxd !! 🎉

I like the idea to translate the slugs. It's a feature that brings a lot of possibilities. I'm going to review the code carefully during the next days! Sorry if I can't provide you fast feedback this time.

Nevertheless, there is an open RFC of Next.js with a similar feature (rewrites), that nowadays it's experimental. Take a look:

* https://github.com/zeit/next.js/issues/9081

I'm not sure if it is possible (or will be possible) to do the same with Next.js.

I would appreciate it if you can add some tests to cover some cases; ex: Not overwriting `/_next` or `/api` folders... What happens in nested alias, or alias with a different dimension, ex:

```js
"/contact": { "it": "/another/path/contatti" }
```

I see that there are a lot of cases to cover. Maybe, in the case that this feature is not covered by the Next.js RFC, we can provide a simple use case just to rename the page and not the full path. 🤔

However, if this feature is part of the Next.js RFC I prefer to don't bring this responsibility to this lib. And maybe I prefer to write some examples and good documentation about how to do it correctly with the Next.js way.

So I recommend you before writing some tests or improvements to this PR, to try the experimental rewrites of Next.js https://github.com/zeit/next.js/issues/9081

I'm also going to experiment with it in the next days to have a better idea of how to achieve this.

**Comment by tonxxd** [comment]
Oh wow didn't know about it, seems exactly what I need. Yes probably is nonsense to implement a customized "rewrite" system when it's already (or will be) handled by next.js

I'll take a look

Thanks ;)

**Comment by tonxxd** [comment]
Indeed I managed to accomplish the slug localization with next.js rewrites, awesome feature!

I am still using next-translate to generate the locale folders and manage the translations. To better handle routes I am using next-routes so if I have to generate a route for products I simply pass the route name to the next-routes Link component and I get back the localized slug with the populated params.(even if this feature could be probably integrated into next-translate Link component).

I think you can reject this pull request since it adds custom logic not needed (and it doesn't handle different alias dimension as you pointed out)

**Comment by aralroca** [comment]
@tonxxd Thank you so much for your effort 👏! I'm going to close it, but what do you think about doing a new PR with an example under `/examples` folder? This would be very helpful for some people!

**Pull request closed without merging**
