### PR TITLE
Add keySeparator configuration option

### PR DESCRIPTION
**Pull request by testerez**
| Option | Description | Type  |  Default |
| ------- | ----------- | ------ | -------- |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
| `keySeparator`   | Change the separator that is used for nested keys. Set to `false` to disable keys nesting in JSON translation files. Can be useful if you want to use natural text as keys. | `string` &#124; `false` | `'.'` |

**Use case:** I'd like to be able to use natural text as keys. This improves the developer experience because I don't have to come-up with a key for each of my texts. Also, I'm using [`i18next-parser`](https://github.com/i18next/i18next-parser) so I don't even have to touch translation files most of the time.

For info, i18next offers a similar option: https://www.i18next.com/overview/configuration-options

### CODE REVIEW

**Review by aralroca — APPROVED** [review]
Thank you for your contribution @testerez! I think it is perfect. Thank you!

**Comment by aralroca** [comment]
@all-contributors please add @testerez for code

**Comment by aralroca** [comment]
@testerez I pre-released under [1.3.0-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.3.0-canary.2). Thanks for your contribution.

**Comment by testerez** [comment]
Thanks for the quick review!

**Pull request merged**
